# Generated by Django 3.0.4 on 2020-08-10 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pjecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
