# Generated by Django 3.0.4 on 2020-08-11 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pjecommerce', '0004_auto_20200810_2057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='oredered',
            new_name='ordered',
        ),
    ]
